### PR TITLE
be able to show/hide content layouts

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by datakurre** [comment]
@vangheem What exactly? Be able to select, which layouts are available on content layout picker? (Change layout overlay)

**Comment by vangheem** [comment]
Maybe these screenshots will help:

You might see something like this::

screen shot 2015-10-08 at 6 18 19 am

So you'll want to hide layouts so they don't show available::
screen shot 2015-10-08 at 6 19 19 am


Also in here, if only one layout is available, it auto selects it. I think @agitator was looking for this.

**Comment by agitator** [comment]
nice!

**Comment by vangheem** [comment]
sigh, I don't understand why this is failing: https://travis-ci.org/plone/plone.app.mosaic/jobs/84341136

the bower install command works locally.

**Comment by datakurre** [comment]
Maybe bower has some user global cache. Well, I'll check this and merge then. 

Nathan Van Gheem kirjoitti to lokakuuta 8 20:16:41 2015 GMT+0300:

**Comment by datakurre** [comment]
@vangheem I cleared build caches at Travis (node_modules and components are cached) and build passed. Weird bower. Travis caches can be cleared from the repo specific settings menu.

nayttokuva 2015-10-08 kello 22 52 14

**Comment by vangheem** [comment]
@datakurre thanks!

**Comment by datakurre** [comment]
@vangheem Thank you for being able to work on this.

**Pull request merged**
