### PR TITLE
Add queue for tile auto-save requests to git less change for write conflict errors

### PR DESCRIPTION
**Pull request by datakurre**
/cc @tomgross

### CODE REVIEW

**Comment by tomgross** [comment]
Hi @datakurre 
Thanks for the patch. Unfortunately we are still facing ConflictErrors. Maybe because all our contenttypes are folderish via. collective.folderishtypes?

This is what happens if I only edit a RichText field a couple of times and pressing save without leaving the focus of the TinyMCE editor.
```
2017-02-27 12:07:16 INFO ZPublisher.Conflict ConflictError at /Plone/de/asd/@@edit: database conflict error (oid 0x9776, class collective.folderishtypes.dx.content.FolderishDocument, serial this txn started with 0x03bd99bb32ea1522 2017-02-27 11:07:11.933059, serial currently committed 0x03bd99bb43de8122 2017-02-27 11:07:15.906834) (1 conflicts (0 unresolved) since startup at Mon Feb 27 08:54:53 2017)
```

**Comment by tomgross** [comment]
I investigated a little further. The conflicting transactions are no AJAX requests triggered by the mosaic editor but by z3cform.applyChanges. So it must have to do something with subrequests (sigh, again!).

```
http://localhost:8008/Plone/de/123-2/@@edit-tile/plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484
http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c
```

Limiting the zserver threads to 1 makes the conflicts go away.

**Comment by datakurre** [comment]
Thanks Tom. Could you check what you see in Z2 log after pressing "Save"? I expect that there might still be a race condition with z3cform inline validation (which does write because of drafting), but maybe there's still something else.

Fixing drafting needs a little more work. Relying on inline validation does not fully work currently and has uncontrolled timing.

**Comment by tomgross** [comment]
I turned off drafting for testing but the ConflictErrors still persists. Here is a example Z2 Log:

```
10.0.2.2 - admin [27/Feb/2017:13:02:37 +0200] "GET /Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c HTTP/1.1" 200 209209 "http://localhost:8008/Plone/de/123-2" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:37 +0200] "GET /Plone/config.js HTTP/1.1" 200 17573 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:37 +0200] "GET /Plone/de/123-2/++resource++orderedselect_input.js HTTP/1.1" 200 3908 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:39 +0200] "POST /Plone/de/123-2/@@plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484?_layouteditor=true HTTP/1.1" 200 1031 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:39 +0200] "POST /Plone/de/123-2/@@edit-tile/plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484 HTTP/1.1" 302 426 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:39 +0200] "GET /Plone/de/@@qsOptions HTTP/1.1" 200 100694 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:40 +0200] "GET /Plone/de/123-2/@@plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484 HTTP/1.1" 200 441 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:44 +0200] "POST /Plone/de/123-2/@@edit HTTP/1.1" 302 339 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:44 +0200] "POST /Plone/de/123-2/@@edit-tile/plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484 HTTP/1.1" 302 426 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:45 +0200] "GET /Plone/de/123-2 HTTP/1.1" 200 47694 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
10.0.2.2 - admin [27/Feb/2017:13:02:45 +0200] "GET /Plone/de/123-2/@@plone.app.standardtiles.html/694f6fcc-c0ba-4624-ad0e-a5fbc5018484 HTTP/1.1" 200 1034 "http://localhost:8008/Plone/de/123-2/edit?_authenticator=d1d6362e13d5d5cd60c29b415af2e3e335ddb26c" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
```
The critical part are the 2 last POST request.

**Comment by datakurre** [comment]
Thanks. One more check: did you remember to compile Mosaic bundle? (I did not include built bundle in my patch.)

**Comment by tomgross** [comment]
Yes. I did compile the "mosaic bundle"

**Comment by datakurre** [comment]
Thanks. I'll look again into this. That POST order on log really looks wrong...

**Comment by datakurre** [comment]
@tomgross I found an issue where text tile auto save did still have a race condition with saving when the tile was selected when pressing save. I did two additional fixes:

* all tiles are blurred / deselected when save is clicked (this will trigger the queued html-tile auto-save)
* inline-validation calls (for drafting support) are disabled with a flag during save

With these changes (even after the first one) I was no longer able to reproduce the issue myself.

**Comment by tomgross** [comment]
Thank you so much @datakurre ! I owe you a :beer: My first tests are very promising. I'll test with some real data soon and merge if this passes.
If this works p.a.mosaic is ready for a 2.0 release. What do you think?

**Comment by datakurre** [comment]
Let's do that. It's long due. I don't need :beer:, but it would be great to see you in Finland next summer at http://www.coactivate.org/projects/midsummer-sprint-2017 :)

**Comment by tomgross** [comment]
@datakurre I'd love to come but the wedding of my brother is at the same time.

**Comment by tomgross** [comment]
Adding and saving works like a charm _but_ on delete I get these errors:

```
2017-02-28T15:47:40 ERROR Zope.SiteErrorLog 1488293260.360.652878374536 https://webcms0.test.fhnw.ch/de/changelog/@@delete-tile/plone.app.standardtiles.html/d446b56f-084c-45dd-9104-ac644c0c5950
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.app.tiles.browser.base, line 73, in update
  Module plone.z3cform.fieldsets.extensible, line 64, in update
  Module plone.autoform.form, line 34, in updateFields
  Module plone.autoform.base, line 133, in updateFieldsFromSchemata
  Module plone.autoform.base, line 160, in _cleanup_rules
TypeError: 'NoneType' object has no attribute '__getitem__'
```
I _think_ I have not seen them before. @datakurre Do you think they are related?

**Comment by datakurre** [comment]
Which plone.autoform? The 1.7.x has issues with tiles. Latest 1.6.x should work find.

https://github.com/plone/plone.autoform/issues/20

**Comment by tomgross** [comment]
Ah ok. Thanks!

**Pull request merged**
