### PR TITLE
Fix for TinyMCE dropdown menus in richtext-tile

### LINKED ISSUE #465: Style selector in tinymce toolbar on inline Richtext Tile broken
In Plone coredev (5.2.2.coredev) the styles selector in the floating toolbard of the RichtText Tile is broken. 

style selector inline richtext mosaic

The problem is a side effect/regression of a fix done for TinyMCE's menus rendering  off-position when TinyMCE is loaded in a pat-modal.  

I submittted this bugreport in 2019: https://github.com/plone/mockup/issues/867
It was fixed early 2020 with this patch https://github.com/plone/mockup/pull/920

Which I improved in https://github.com/plone/mockup/pull/945 because the original patch didn't take into account there could be more than one TinyMCE on a  page (or in a modal).

A while after implementing this patch in customer projects with mosai I noticed that while the 'native' tinymce menu's etc. are now working, there are at least two regressions:

1. This one where the floating inline tinymce toolbar seems now bound by the container id

2.  'sub'-modal's from some plugins in TinyMCE that open their own modal now get similar displacement issues: the optional but useful template plugin for TinyMCE as documenten at https://docs.plone.org/adapt-and-extend/config/templating.html#configure-templates has a pull down menu for selecting the template and it is completely broken.

If I revert #920/#945 by removing binding to a container_id in the tinymce pattern.js, the above two problems disappear, so I'm fairly sure these issues are related.  

So..... either we have tinymce's own menu's not working in a modal, or we break the floating toolbar and sub-modals.

I've been tinkering with the #940 patch to not only check for .plone-modal-dialog as a parent class, but see if binding to the container also works for the floating toolbar in the richtext tile, but no success so far.  

Another direction without any guaranteed return on time invested to fix this, is upgrading TinyMCE itself with the hope that this might be fixed, see https://community.plone.org/t/list-of-tinymce-defects-in-plone-5-2-call-for-fixing-issues-and-participation in the later comments. 

@thet I've seen other issues from you where you effectively replace pat-modal with another implementation, is pat-modal root cause here as well? @cillianderoiste ?

### PR DESCRIPTION
**Pull request by petschki**
fixes #465

### CODE REVIEW

**Comment by fredvd** [comment]
@petschki Why asking you for a review if you can't wait 8 working hours?  You post a review in the evening and remove it early in the morning?

**Comment by petschki** [comment]
@fredvd sorry for that 😬 belgium 🍺 as compensation in Namur?

**Comment by agitator** [comment]
@fredvd :chocolate_bar: :wink:

**Comment by fredvd** [comment]
Just nagging. Wanted to check your fix last evening, but  got stuck in a MutationObserver and a gulpfile refusing to parse ES 6 last evening. Until I figured out that naming the thing gulpfile.babel.js only activates ES 6 transpiling in the gulpfile, not in the processes JS.

**Pull request merged**
