### PR TITLE
Adapt to changes in plone.app.blocks and cleanup initial configuration

### PR DESCRIPTION
**Pull request by datakurre**

### CODE REVIEW

**Comment by datakurre** [comment]
@vangheem 

All the stuff discussed at https://github.com/plone/plone.app.mosaic/issues/130#issuecomment-138334636

And these already in blocks' master

https://github.com/plone/plone.app.blocks/commit/af9960f86a0e4e1152a46c98deff36dce665cc85
https://github.com/plone/plone.app.blocks/commit/b3da01ee650cda487022dc6828ef118abb48c806

**Comment by vangheem** [comment]
Looks great!

**Comment by datakurre** [comment]
@vangheem Does ``for=`` in content layout manifest support multiple types? News Item could probably use document's default layout before it has better alternative, but it should either have multiple types in for or be registered twice.

**Comment by datakurre** [comment]
Well, probably layout's path is also used as token, so it's not possible to register same layout twice. Maybe just copying document.html to news_item.html would be the right thing to do.

**Comment by datakurre** [comment]
Copied document layout into news item layout https://github.com/plone/plone.app.mosaic/commit/c7a36d121c0495b32fedcd5de1cb85c8feabb0a1

**Comment by vangheem** [comment]
It supports multiple. Comma separated.

**Pull request merged**
