### PR TITLE
Enhance docs

### LINKED ISSUE #253: Improve Mosaic Documentation
Content layouts
- [ ] Restricting content layouts globally
- [ ] Restricting content layouts per content type
- [ ] Restricting, who can create new content layouts
- [ ] Restricting, who can change content layouts
- [ ] Adding unmovable tiles into content layouts (removing class 'movable' from 'mosaic-tile')
- [ ] Adding non-removable tiles into content layouts (removing class 'removable' from 'mosaic-tile')
- [ ] Adding readonly tiles into content layouts (adding class 'mosaic-read-only-tile' into 'mosaic-tile')
- [ ] Restricting amount of columns available in layout
- [x] ~~Adding editable HTML area (raw html tile) into content layout~~

Editor
- [ ] Hiding a tile from insert menu
- [ ] Moving a tile in insert menu
- [x] ~~Adding a new HTML template tile into insert menu~~
- [ ] Adding a new custom (Python based) tile into insert menu
- [ ] Adding a new action into TinyMCE editor https://github.com/plone/plone.app.mosaic/issues/200
- [ ] Hiding tile formats from format menu
- [ ] Adding a new tile format into format menu
- [ ] Hiding row formats from format menu
- [ ] Adding a new row format into format menu

### PR DESCRIPTION
**Pull request by datakurre**
This pull request is for reviewing, fixing and merging docs written during Mephisto sprint

Would fix #253

### CODE REVIEW

**Comment by AnneGilles** [comment]
I just added that other email address to settings... and now?

**Comment by gforcada** [comment]
@AnneGilles as soon as you make a change or close and re-open a pull request mr.roboto (the thing behind does checks) runs again.

**Comment by gforcada** [comment]
@datakurre @plone/documentation-team where is this going to be uploaded?

**Comment by datakurre** [comment]
Currently Mosaic builds at Travis and uploads to S3. The link is in README.

**Comment by AnneGilles** [comment]
once the docs have been polished they should go to readthedocs imho. that would make for a nicer URL.

good to see it here now, though:

http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/latest/getting-started.html

**Comment by datakurre** [comment]
Unfortunately we cannot autogenerate screenshots at RTD, but we should be able to integrate with docs.plone.org.

**Comment by AnneGilles** [comment]
@datakurre right! docs.plone.org is the better place for this.

**Comment by jensens** [comment]
may we better just rebase and merge this and then improve further?

**Comment by AnneGilles** [comment]
@thet once you are at it, you may give the docs some love?

**Comment by jensens** [comment]
I merge this now. Better now than never!

**Pull request merged**
