### PR TITLE
Layouts editor control panel

### PR DESCRIPTION
**Pull request by vangheem**
This PR adds a TTW layout editor control panel.

screen shot 2015-08-06 at 10 13 59 pm
screen shot 2015-08-06 at 10 14 03 pm
screen shot 2015-08-06 at 10 14 13 pm

### CODE REVIEW

**Comment by datakurre** [comment]
Looks awesome! Thanks!

**Comment by ebrehault** [comment]
@vangheem I think that's great.
In https://github.com/plomino/rapido.plone, I also had to provide a convinient way for users to edit code (HTML, but also Python) TTW so they can customize their site rendering and behavior.
I decided not to activate the File manager pattern in a Rapido specific control panel (as you did here), but just to use the existing Theming editor (people go to the Theming editor and just by creating a folder named `/rapido`, they can start customizing stuffs handled by Rapido).

I think there are several benefits with this approach:
- first, consistency: the Theming editor is the unique place where users go to hack into their site rendering,
- secondly, versatility: plone.app.theming allows to work TTW of course, but also in the file system (in the /theme of our skin module), it also allow to import/export the entire site design as ZIP files, to copy an existing theme to change it a little bit, etc.

Note: I would love to discuss that with you and @datakurre, but I am leaving for holidays today's evening, so I won't be online for a while.

**Comment by datakurre** [comment]
@ebrehault @vangheem Layouts are stored using plone.resource similarly to themes and adding zip import/export etc should be trivial (actually, I'm puzzled, why we don't have generic editor for plone.resource directories yet [UX reason, probably, to prefer use-case specific editors]).

I would like to keep layouts separate from themes on plone.resource level (keep the different resource directories), but unifying the editing UX would be nice.

Yet, this would require a zip format and import/export, which could populate multiple resource directories....

So, yes, dumping everything into theme directories would be easy and workd already, but feels still dirty (and loses some potential of plone.resource).

**Comment by ebrehault** [comment]
I hear you.
We probably need to have a more global discussion about how the TTW/hacking/customization story should be delivered to our users.
Let's do that at the Bucarest ploneconf.

**Pull request merged**
