### PR TITLE
Change edit and delete tile buttons

### PR DESCRIPTION
**Pull request by vangheem**
To both be placed in bottom right corner. Delete has a confirmation dialog to prevent accidental deletion.

### CODE REVIEW

**Comment by datakurre** [comment]
mosaic-editor-drop-field-text-tile

@tomgross What would you think?

**Comment by thet** [comment]
For my taste, that looks a bit clumsy. Doesn't the button get in the way for long texts?
What about a X in a circle like seen in a lot of modals or lightbox overlays? E.g. the ``glyphicon-remove-circle`` from http://getbootstrap.com/components/ ?

**Comment by vangheem** [comment]
Yes, it may. It is still "WIP" since I knew this wasn't going to be perfect...

Maybe it only shows when you are in active hover and fades out when you are typing for instance.

**Comment by vangheem** [comment]
The button should be smaller probably as well...

**Comment by thet** [comment]
Ah, fading out when typing is nice!
But I think the remove-circle style would be a better fit - but I don't know if that's just personal taste.
I can provide the styles if you want.

**Comment by vangheem** [comment]
Sure, any help with styling would be appreciated!

**Comment by thet** [comment]
Fine, I'll come up with something later today!

**Comment by thet** [comment]
+1 for merging - not sure if I'm able to contribute something today.
The icon design can be changed anytime!
I'd like to use font-awesome. Is this an option?

**Comment by datakurre** [comment]
If try to be good semver citizen now, this probably makes it 1.1 (as long as changes are P4 compat, I can still do 1.x releases).

:-1: for font awesome, because it's not used in core. If we need custom glyphs, we need to add custom fot using the same glyphfontbuilder with Plone core (so that those could be merged into Plone font later).

**Comment by thet** [comment]
If P5, we can at least use glyphicons, because they are part of Bootstrap/Plone5...

**Comment by thet** [comment]
But I'd merge this when ready and I'll do visual changes to the buttons in a separate PR.

**Comment by datakurre** [comment]
@thet OK for a separate pull.

FWIW glyphicons are removed in BS 4.

**Comment by vangheem** [comment]
We've been using svg lately... We have clients on locked down IE computers that block any custom fonts(and then, font icons). We've actually had to replace all the font icons in plone's UI with svgs...

**Comment by vangheem** [comment]
Alright, been testing for a few days, this seems okay. I'd like more opinions on it though--if the confirmation dialog is too annoying or if there is a better way to do confirmation? I have taken it out of WIP.

**Comment by datakurre** [comment]
@vangheem One previous proposal to avoid dialog was requiring two clicks/press withing some time period for delete (e.g the first turns it red [or something] and the second removes).

But dialog is ok, until we have something better.

**Comment by vangheem** [comment]
I can spend some time on that idea.

**Comment by vangheem** [comment]
Alright, updated again with the 2-click idea.

**Comment by datakurre** [comment]
:+1: I'm travelling this weekend, but can do release early next week,

**Comment by thet** [comment]
@vangheem you're right using SVGs! I just read https://github.com/blog/2112-delivering-octicons-with-svg which makes me feel preparing a PLIP about replacing iconfonts with SVGs.

**Comment by vangheem** [comment]
@thet if there is anyone interested in replacing font icons with svgs, talk to @RobZoneNet first. We did it for much of plone already. Not sure if it should be in core and there are drawbacks to how we've done it so we might need to think of a more clever long term solution. We can discuss in another thread though perhaps.

**Comment by jensens** [comment]
+1 for SVGs - which can be easily put inline (also later using a transform) to avoid many requests.

**Comment by jensens** [comment]
But state here is ready for merge, right?

**Comment by datakurre** [comment]
@vangheem Thanks again.

**Pull request merged**
