### PR TITLE
Be able to edit properties

### PR DESCRIPTION
**Pull request by vangheem**
Fixes problem where you can not edit properties on layout pages.

### CODE REVIEW

**Comment by datakurre** [comment]
What was happening here? I recall that properties overlay directly changed the fields on underlying edit form and therefore there was no way to "cancel" those edits.

It seems that this pull reveals the original add / edit form buttons? Does both cancel and save on properties form now leave the editor instead of just closing the overlay?

Nathan Van Gheem kirjoitti to heinäkuuta 9 09:24:28 2015 GMT+0300:

**Comment by datakurre** [comment]
Also, I recall this same "overlay" being used when editing individual field tiles. For example, when you are editing an event and have field tile for event start datetime, clicking (i) in that tile opens overlay with only that field. (Again, old code and behavior from deco editor...)

Nathan Van Gheem kirjoitti to heinäkuuta 9 09:24:28 2015 GMT+0300:

**Comment by vangheem** [comment]
Yes. Here is what is going on:

- editing field tile edits the underlying field on the original edit form. This is actually rather smart and I don't mind this approach but field editing is very odd.
- mosaic was hiding the Save button so you couldn't edit any of the other properties.
- With this PR, cancel button just closes the overlay instead of reloading the page(like it did before)

I'm going to look into this further. I still don't think I have the full picture.

@datakurre how does one run the robot doc tests for this package using coredev 5.0 buildout?

**Comment by datakurre** [comment]
@vangheem bin/pybot src/plone.app.mosaic/docs

I apologize for re-introducing this new kind of doc tests.

About field editing. I think, the idea was to make all fields inline editable (similarly to text and richtext field being editable using TinyMCE), but it may also be too much work (I think, one of the ugliest parts in editor code is th eone handling text and richtext fields).

How did hiding Save button prevent from editing any other properties? I don't understand.

Also, I think, Cancel is misleading here, because just closing the overlay doesn't cancel the made changes. Changes are still present in the hidden add / edit form and saved with the page save.

That all said, I don't know how much Rob (and other Deco designers) did iterate to reach the current UX. I try to be open for better options.

**Comment by vangheem** [comment]
Inline editing all fields won't work I don't think. I think the form needs to persist.

The real issue here is me not understanding the complete picture of how editing works. Basically, you edit the field in the properties overlay, close it, then use that other save button.

I think it's a bit wonky and users will get hung up on it(I did). I'm going to think about it more. I'll let you know when this PR is worth looking reviewing again.

**Comment by datakurre** [comment]
@vangheem Yes. That how it is (because overlay really just shows the underlying add / edit form, the field values are always changed, but saved only with the page save), and agreed, it does not give you good feedback that properties are modified (with closing the overlay) and will be saved during the page save. In that sense, it's probably different from all other overlays in Plone.

**Comment by vangheem** [comment]
closing this. Might revisit later.

**Pull request closed without merging**
