### PR TITLE
WIP: Allow editors to be abe to save layouts

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by datakurre** [comment]
Thanks again @vangheem!

Would it do too much harm to leave interface-attribute off from those registry entries with IBundleRegistry? Once I manage to make next set of releases, I'll branch 4.x off from master.

**Comment by datakurre** [comment]
It's mandatory, of course... I'll think something....

**Comment by datakurre** [comment]
Well, I seemed had already monkeypatch-added those interfaces to Plone 4, so I just updated them.

**Comment by datakurre** [comment]
:+:1

**Comment by vangheem** [comment]
This is going to end up needing a release of blocks: https://github.com/plone/plone.app.blocks/pull/26

**Comment by vangheem** [comment]
Still working on it but so far...:

- save layout button
- user can save global layout
- user can save layout so it is just available to that user

to do/what to think about:

- What do you do about old layouts?
- If a user deletes, what about content that was referencing it? Things get messy here...
- This is still controlled by a permission so only special users should have this ability but I still see this is a point of abuse..
- The reason I went with the "global" vs "user" layout is because I'm trying to prevent the scenario where there is layout overload

**Comment by datakurre** [comment]
What if you don't allow users to really delete layouts, but deleting just disables (and hides from layout menu)? Trying to save new layout with an existing name would result in -1, -2, ... postfixing, similarly to dx content.

It's not optimal, but the easiest solution and keeping layouts don't take much storage. Maybe we can later have tool to clear unused layouts. Also linkintegrity-like stuff is possible, but would add complexity.

**Comment by vangheem** [comment]
Those were exactly the 2 ideas I had. The first is the most simple and safe idea.

Other thoughts:
- do we allow overwriting overwriting existing layouts?
- do we keep all the tile data in the layout or clear it when we save?

**Comment by vangheem** [comment]
I'm leaning toward adding a new index so we can track and manage layout settings for existing objects. I just don't see another way... What if a user wants to move a layout from a personal one to a global one for instance. Need a way to touch all existing layouts. A user would probably also what to know things like how many objects are using a certain layout. Thoughts?

**Comment by vangheem** [comment]
also, I can't get the tests to run. I'm getting this::

```
Module: plone.app.mosaic.tests.test_setup

Traceback (most recent call last):
  File "/Users/nathan/code/coredev5/src/plone.app.mosaic/src/plone/app/mosaic/tests/test_setup.py", line 2, in <module>
    from plone import api
  File "/Users/nathan/buildout-cache/eggs/plone.api-1.5-py2.7.egg/plone/api/__init__.py", line 3, in <module>
    from plone.api import content
  File "/Users/nathan/buildout-cache/eggs/plone.api-1.5-py2.7.egg/plone/api/content.py", line 8, in <module>
    from plone.api import portal
  File "/Users/nathan/buildout-cache/eggs/plone.api-1.5-py2.7.egg/plone/api/portal.py", line 13, in <module>
    from plone.app.layout.navigation.root import getNavigationRootObject
  File "/Users/nathan/buildout-cache/eggs/plone.app.layout-2.5.18-py2.7.egg/plone/app/layout/navigation/root.py", line 6, in <module>
    from Products.CMFCore.utils import getToolByName
  File "/Users/nathan/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/__init__.py", line 15, in <module>
    import PortalFolder
  File "/Users/nathan/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/PortalFolder.py", line 20, in <module>
    from AccessControl.SecurityInfo import ClassSecurityInfo
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/__init__.py", line 16, in <module>
    from AccessControl.Implementation import setImplementation
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/Implementation.py", line 96, in <module>
    setImplementation("C")
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/Implementation.py", line 51, in setImplementation
    from AccessControl import ImplC as impl
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/ImplC.py", line 34, in <module>
    from AccessControl.ImplPython import SecurityManager
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/ImplPython.py", line 42, in <module>
    from AccessControl.ZopeGuards import guarded_getitem
  File "/Users/nathan/buildout-cache/eggs/AccessControl-3.0.12-py2.7-macosx-10.4-x86_64.egg/AccessControl/ZopeGuards.py", line 22, in <module>
    from RestrictedPython.Utilities import utility_builtins
  File "/Users/nathan/buildout-cache/eggs/RestrictedPython-3.6.0-py2.7.egg/RestrictedPython/Utilities.py", line 41, in <module>
    utility_builtins['DateTime']= DateTime.DateTime
AttributeError: 'module' object has no attribute 'DateTime'
```

**Comment by vangheem** [comment]
Nice, robotframework has a global DateTime module.

**Comment by vangheem** [comment]
FYI, using version pins from https://raw.githubusercontent.com/plone/plone.app.robotframework/master/versions.cfg fixes things. So if you're developing in coredev, need to add them...

**Comment by datakurre** [comment]
@vangheem RobotFramework's DateTime issue should have been fixed in p.a.robotfarmework >= 2.9.x. That was the reason, why we pinned 2.8.4 for a so long time.

**Comment by datakurre** [comment]
@vangheem The index could also be just zope.index based utility, or maybe even relation in zc.relations, but maybe portal_catalog is the easiest one for everyone else to understand. I don't oppose indexing (and all the features it makes possible). It just felt like a lot of work.

About cleaning tile data. That's also a rabbit hole, but probably it should be done. Probably we should have a generic utility function in plone.app.blocks to resolve all the currently used tiles from layout. (That's always been the ugly part of blocks + tiles: used tiles can only be parsed from layout. And we've made it a bit more complex with shared layouts.)

The best place to clean up old tile data is probably the end of drafting.py in plone.app.tiles. There's already a code for cleaning up data for explicitly deleted tiles.

**Comment by vangheem** [comment]
Well, it's pretty close. Users can delete old layouts now and reassign existing content to replacement layouts. However, this requires a new catalog index--don't hate me.

The JS is getting ugly for those modals. Sigh, I wish we could use react or something :(

So one thing I did which I should not have problem as part of this PR is remove the unused JS tests. Should I add them back in and see if we can revive them?

What is desired for testing here? Do we want to continue with everything tested as part of the robot sphinx docs? I'd like to add more tests before this is merged.

I also noticed that the current robot test doesn't quite work with dropping the tile properly. I played with it for a bit but couldn't get it to work. Testing these things is tough.

**Comment by vangheem** [comment]
And the CI fails because of plone.app.content.

**Comment by datakurre** [comment]
@vangheem With new catalog indexes I've used to add a such default indexer for zope.interface.Interface that it only raises AttributeError. AFAIK that's the fastest way to make uninteresting content to skip certain index.

Once plone.restapi is ready, it should make sense to start rewriting the layout editor on top of react and restapi. (I really like, how well react + redux works for building widgets and serializing complex field data.)

That and broken JS test story is because, I've only recently caught up with the current JS technologies. Those JS tests have have not been run since the refactoring started in Barcelona Mosaic sprint, show they may be really rotten. Robot tests are there, because I didn't know, how to properly implement JS testing, and I also wanted up-to-date screenshots.

**Comment by datakurre** [comment]
@vangheem plone.app.blocks = 3.1.0 is now released

**Comment by datakurre** [comment]
@vangheem Is something still missing from this? (Clearing unused persistent tiles is still missing, but that can be introduced later.)

**Comment by vangheem** [comment]
If you agree with this, it can be merged. You might want to give it a test yourself.

Only other thing I was going to try on this branch was moving the "delete" button.

**Comment by datakurre** [comment]
Thanks. I try this out. This has been requested, so I'm grateful that you managed to do this.

Delete button is unrelated and probably bundles with other UI changes, so probably it's better in a separate pull.

If I don't see any blocking issues, I make an rc-release after this. 

Nathan Van Gheem kirjoitti ke huhtikuuta 6 15:55:09 2016 GMT+0300:

**Comment by datakurre** [comment]
@vangheem FYI: I merge this as soon as I get doctest (dropping tile) figured out. It's insane that it's still that hard with Selenium.

**Comment by vangheem** [comment]
Yikes. That is not fun figuring out. It's so hard doing drag drop and mouse positioning type actions with selenium and robot...

**Comment by datakurre** [comment]
Even less when it works locally, but not at Travis.

**Comment by vangheem** [comment]
Thanks @datakurre!

**Comment by datakurre** [comment]
Thanks @vangheem !

**Pull request merged**
