### PR TITLE
Improve tinymce toolbar sticky computation

### PR DESCRIPTION
**Pull request by frapell**
When there are several richtext tiles, the computation for making the toolbar "sticky" is not using the "active" toolbar

This fixes that issue and also includes the Mosaic toolbar at the top to decide when to make the toolbar sticky or not

### CODE REVIEW

**Comment by frapell** [comment]
@datakurre Do you think this could be merged to master?

**Comment by datakurre** [comment]
It looks good to me, but I’ve fallen behind the master and would prefer someone with up to date Mosaic merging it.

**Comment by frapell** [comment]
@petschki Since you were the latest to merge a PR to master, would you mind checking this one?

**Comment by frapell** [comment]
@petschki Ouch, totally missed your request... thank you for doing it, and for the merge! :)

**Pull request merged**
