### PR TITLE
Add support for (static) centrally managed content layouts with locally editable tile configuration

### PR DESCRIPTION
**Pull request by datakurre**
WIP, but created this pull for one place to discuss and work on this.

### CODE REVIEW

**Comment by datakurre** [comment]
@vangheem There was a minor issue in plone.app.tiles.drafting preventing save of customized tiles (https://github.com/plone/plone.app.tiles/commit/00387429de7e4d0046be538da438472b5824e1d8 [I was trying to be too clever there; now it's back to the original code from Deco]).

Now static rawhtml tile has toolbar and can be saved, but editor doesn't know yet how to load it (tile is rendered correctly on display mode, but empty in editor).

**Comment by vangheem** [comment]
Yes, its a configuration problem. The toolbar is actually just empty. I
couldn't figure it out in the short time I tried.

**Comment by datakurre** [comment]
@vangheem Sorry, mean I fixed the toolbar in configuration, but was talking about the tile contents. Contents are saved, displayed on view, but not loaded for edit (that was never implemented in the original code).

**Comment by vangheem** [comment]
It's working for me now with your toolbar config fix

screen shot 2015-08-23 at 7 03 50 am

**Comment by datakurre** [comment]
Good to know. I admit trying only briefly and with Plone 4 ;) Need to look into beginning to update robot doc tests next (when time).

Have you already thought about also being able save "contents layouts" from editor somhow?

Nathan Van Gheem kirjoitti su elokuuta 23 15:04:35 2015 GMT+0300:

**Comment by vangheem** [comment]
Yes. It should be very easy to add a "save layout" button. It's important we implement permissions and role mappings for being able to customize layouts and saving new layouts.

**Comment by datakurre** [comment]
@vangheem Your screenshot had add form. Does the rawhtml still get its saved data on edit form?

**Comment by vangheem** [comment]
It was before. I'm afk right now. Can try later.

**Comment by datakurre** [comment]
No hurry. To know that is enough for me. Also afk today :)

> Nathan Van Gheem <notifications@github.com> kirjoitti 23.8.2015 kello 17.49:
> 
> It was before. I'm afk right now. Can try later.

**Comment by datakurre** [comment]
@vangheem My issue was just a simple typo in Plone 4 bbb. Yet, thanks for thinking about Plone 4 in that :)

I like this. I guess, besides TODO features, the only issue here is the issue with X-Persistent-Tile flag. Because of ESI, I see really just the two options:

a) postfixing tile URLs in content layout (and caching the result to avoid parsing the same layout multiple times) in behavior view

b) changing plone.tiles to always lookup for the possible persistent tile data (so that X-Persistent-Tile flag would be needed only when saving the tiles from Mosaic Editor with POST, and the flag could then be an extra header instead of query param).

The current implementation is a) without caching. Maybe you remember at some point, what was the issue with initial implementation of b).

Meanwhile, you could continue polishing Mosaic for your use-case, and I'll be slowly updating the documentation to test and screenshot this feature. (Also normal tests would be great, but personally I wil will priorize documenting the usage)

**Comment by vangheem** [comment]
Forgot about referencing this branch too! https://github.com/plone/plone.app.tiles/tree/layout-fixes

**Comment by datakurre** [comment]
@vangheem Do you think that behavior in p.a.tiles is necessary? I already changed master to simply copy all drafted tiles and not do that heuristic checking from layout, and made plone.app.tiles to not depend plone.app.blocks at all.

With static content layout it's now possible that content instance will hold persistent tiles, which are no longer used in the current layout. Maybe, instead of more complex draft synching, we could have IObjectModifiedEvent handler in plone.app.blocks, which would then clean un-used tiles. It would be natural in p.a.blocks, because it will have also the layout code.

**Comment by vangheem** [comment]
@datakurre That is fine doing it that way and yes, I think using an IObjectModifiedEvent subscriber in plone.app.blocks makes sense.

**Comment by vangheem** [comment]
these PRs need to be merged first:

https://github.com/plone/plone.app.blocks/pull/20
https://github.com/plone/plone.app.standardtiles/pull/16
https://github.com/plone/plone.tiles/pull/4
https://github.com/plone/plone.app.tiles/pull/5

Then, we can make alpha releases of those packages that plone.app.mosaic can depend on so these travis tests can run.

@datakurre can you take a look?

**Comment by vangheem** [comment]
I'm also not really sure about what to do with tests. Seems like plone.app.mosaic is just running CMFPlone robot tests with mosaic installed. With how things are now, this will break things. Can you confirm?

I think we just need our own robot tests and not call CMFPlone tests.

**Comment by datakurre** [comment]
@vangheem Are you in hurry to get this merged? I'd be able to fix the tests on this Friday.

Mosaic runs CMFPlone tests just in case, because it overrides main_template view to make site layouts work also on all main_template based views (and viewifies main template for Plone 4). Because many Mosaic users are not using site layouts, maybe we should make main_template override conditional with zcml:condition="has mosaic-site-layouts" feature flag.

Mosaic Editor is tested with Robot doc tests in docs. I could fix those on Friday.

**Comment by datakurre** [comment]
Merged https://github.com/plone/plone.app.standardtiles/pull/16 but just closed https://github.com/plone/plone.app.tiles/pull/5 because we had better idea about that.

**Comment by vangheem** [comment]
No rush! Just forgot about it as I've been working off of branches and thought I should organize.

**Comment by datakurre** [comment]
Did so much small tweaks that only had time to fix the existing "Getting started" tour screenshots to make the Travis build pass:

 - http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/577/577.1/getting-started.html
 - http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/577/577.2/getting-started.html

@vangheem FYI that I did rename "tinymce_"-prefixed settings into "richtext_"-settings (in hope that we get that new editor later, which ploneintranet backed). Upgrade step will clear "tinymce_"-prefixed settings and re-import default configuration.

**Comment by vangheem** [comment]
Thank you @datakurre

**Comment by datakurre** [comment]
@vangheem Thank you too :) plone.tiles and plone.app.tiles have been released. plone.app.standardtiles probably needs some work before release (eg. outputfilters for rawhtml). plone.app.blocks has been merged, but not yet released.

Personally, I'd like to do 1.0b1 after Munich theming sprint at latest (I'm not participating, but @pbauer has been interested in reviewing Mosaic there).

**Pull request merged**
