### PR TITLE
Fix bytestring join in main_template.py

### PR DESCRIPTION
**Pull request by 1letter**
in cook_layout method:
string conversion it should different handled because the XMLSerializer returns bytestring in py3

### CODE REVIEW

**Comment by jensens** [comment]
LGTM, but tests are red. I triggered a master build to see if this might be unrelated.

**Comment by 1letter** [comment]
thats strange, if i start the tests for every job separately on travis, the py3-test are green. if i start all at the same time, all test failing.

**Comment by 1letter** [comment]
Ok, its only a sporadic failure in the test_editor.robot. after click on the save button a alert dialog is displayed. an the handling with this dialog produced the error.
Bildschirmfoto vom 2019-07-24 23-40-36
It depends on the running time, now are 3 tests green.

**Comment by 1letter** [comment]
Ok, after start the last "red" job manually, all is green. thats incredible, no changes on code....

**Pull request merged**
