### PR TITLE
JavaScript: Correctly await the TinyMCE initialization and avoid Tiny…

### PR DESCRIPTION
**Pull request by thet**
…MCE double initialization.

### CODE REVIEW

**Review by petschki — APPROVED** [review]
Lgtm. Testsetup seems broken though.

**Comment by thet** [comment]
@fredvd tnx for your fix! since more is needed i created a separate PR:

https://github.com/plone/plone.app.mosaic/pull/538

**Comment by frapell** [comment]
@thet Not sure if I am doing something wrong? I am pulling this branch, and after running `yarn install` and `yarn build:webpack` I am still seeing both `tinymce` being loaded (mosaic's one is a bit smaller though). Am I missing a step or something? (FYI I am simply opening a mosaic in edit mode with 1 richtext tile in it)

image

**Comment by mauritsvanrees** [comment]
I have rebased on master.  That should fix CI.

**Comment by thet** [comment]
@frapell do is this a bare Plone 6.0 with only mosaic installed? Or are any other addons or tinymce plugins involved?

**Comment by frapell** [comment]
@thet yup, fresh `buildout.coredev` from `6.0` with only mosaic.

Not sure what I need to test though, everything appears to be working ok, except I still see tinymce chunks being loaded twice as reported. But if this fix is unrelated to that, then everything looks fine.

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Pull request merged**
