### PR TITLE
fix reference to default img

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
I didn't really change anything so this shouldn't be failing.

**Comment by thet** [comment]
possibly it's due to some changes @jensens and I were making recently. all of them were passing on their own test suites, but at some point I recognized, that mosaic isn't working any more. I'm going to isolate that problem from tomorrow on...

https://github.com/plone/plone.tiles/pull/7
https://github.com/plone/plone.app.blocks/pull/34
https://github.com/plone/plone.subrequest/pull/9
https://github.com/plone/plone.app.standardtiles/pull/29

**Comment by jensens** [comment]
Both, master and this branch, are running local using the exact same steps as in .travis.yml w/o any failures. This is valid for the tests and also for pybot. Latter fails on Travis CI.

**Comment by datakurre** [comment]
So, sounds like the current failures can probably be attributed to Selenium / Firefox differences. Also phantomjs should be working nowadays, so I'll try that on a separate branch.

**Comment by datakurre** [comment]
Well, I seem to be able to reproduce this (the issue in current master) locally.

**Comment by jensens** [comment]
I just found plone.subrequest is needed from sources, also timing problems in robot. pushed it to master.

**Comment by thet** [comment]
@datakurre can we hook ``Page should contain`` and all those directives to "Wait until" the elements are available? I guess, we could just wait everywhere instead, where we otherwise use directives which check for something being available immediately.

**Comment by datakurre** [comment]
@thet Please do. It adds longer timeout when tests do really fail, but no other harm. Probably drops more false positives than cause real harm.

**Comment by jensens** [comment]
after fixing the tests there is a problem left, see #194

**Pull request merged**
