### PR TITLE
Add ``bootstrapPath`` less variable.

### PR DESCRIPTION
**Pull request by thet**
Now the bundle can be built with ``plone-compile-resources``.
Contains an upgrade step.

### CODE REVIEW

**Comment by jensens** [comment]
probably outdated?

**Comment by thet** [comment]
@jensens I think this could still be relevant for Plone 5.2 on plone.app.mosaic master

**Comment by jensens** [comment]
if so, reopen and merge please.

**Comment by thet** [comment]
done

**Pull request closed without merging**
