### PR TITLE
Optional show all fields

### PR DESCRIPTION
**Pull request by jensens**
Our customer really dislikes the hiding of fields. While keeping here all as-is UI wise, this new "setting" can be used in custom code like so:

```
/* do no hide all fields in mosaic */
require([
    'jquery',
    'mosaic-url/mosaic.overlay',
], function($) {
  'use strict';
  $.mosaic.overlay_hide_fields = false;
});

```

### CODE REVIEW

**Comment by datakurre** [comment]
@jensens Did you see any issues with this? Just wondering, if this should be the new default.

**Comment by jensens** [comment]
From a usability point of view this should be default and I'd really like to have this as default. 
The current behavior feels more like a workaround.
But currently all fields which are editable in the form don't update the editor beyond on close. This need to be fixed (I will look into it).
I also have some issues with TinyMCE in the overlay form (but this is a problem with fields not in the editor beyond anyway).

**Comment by vangheem** [comment]
Maybe show everything except the tinymce fields(text)? IMO, that field should be in the properties form at all..

**Comment by jensens** [comment]
the main problem is that it is called properties. imo it should be an alternative edit form. If there are structured fields i do not want to fiddle clicking here and there all the time in the designed site, but go though a form and fill all relevant data in one after another. this is most important in an add form.

Btw, TinyMCE seems to be broken in the add form only. I frequently have in my projects formatted teaser-text-fields for content that never appear in the site itself, but in listings. So have TinyMCE working in the so-called properties form is a must have.

**Comment by jensens** [comment]
may we merge this tiny change and then I investigate further how to fix tinymce and the update thing?

**Comment by datakurre** [comment]
:+1:

**Pull request merged**
