### PR TITLE
Refactor TinyMCE initialization

### LINKED ISSUE #528: p.a.mosaic 3.0.x, Plone 6.0.2 TinyMCE does half of the time not get initialised in tile edit modals
In  a project I am upgrading from Plone 5.2. to Plone 6.0 we have some custom tiles with multiple RichText fields. Sometimes, about 50% the tinymce doesn't get initialised for any of the richtext fields in the browser and you only see the mimetypeselector:

tinymce richtextfieldwidget

When reloading loading the mosaic edit page and again clicking on the edit, shows a completely random but about 40-60% chance of tinymce loading.  If I also keep the network tab open in the browser and monitor loaded js resources, the  times the initialisation fails, I consistently see a failed 404 request for:

`http://localhost:8080/nl/++webresource++fd4360ae-bfad-5886-999c-a1c8440f3377/++plone++static/bundle-plone/chunks/themes/silver/theme.min.js%E2%80%9D`

If I don't see the error that this resources cannot be loaded, TinyMCE works.  According to @petschki  who assisted me with some debugging on Discord, this separate resource has been removed from the tinymce pattern and should be loaded directly.  -> https://github.com/plone/mockup/blob/master/src/pat/tinymce/tinymce--implementation.js#L168

----

Digging further, I can check the initiator and stack trace of the silver/theme.min.js chunk that's no longer there: 

stack-trace-wrong-resource-load

From that stack trace I can jump to the exact line that inserts/starts the load, which is here.  If I put a breakpoint on that line and reload the page a few times, every time I hit the breakpoint and the passed resource to load is the silver/theme.min.js the tinymce init will fail when I resume from the breakpoint

tinymce-breakpoint-themeresourceload

Also a bit surprising, half of the times when refreshing the page, the breakpoint on the line to load the resource will instead show this resource to load, nd then tinymce initialisation works. 

`http://localhost:8080/nl/++webresource++fd4360ae-bfad-5886-999c-a1c8440f3377/++plone++static/bundle-plone/chunks/langs/nl.js`

----

## Possibly releated issues

* This issue was opened in January by @frapell where he describes that tinynmce chunks get reloaded when they should already be present in the browser.  With the behaviors descrribed above it also seems like non deterministically 'old' or different versions of tinymce get loaded. 
https://github.com/plone/plone.app.mosaic/issues/515

I tried to debug this by having 2 browser windows opened on the network tab, filtering on .min.js javascript resources and creating a working and non working reload next to each other. Then I sorted on the filename and compared EACH of the 50-60 resources. ALL THE SAME chunks get loaded, only the extra silver/theme.min.js 404 is present in the browser network list where TinyMCE doesn't initialise in the modal. 

That seems to bust the theory that a different tinymce gets loaded, but the ordering is somewhat different in each browser refresh, so a race condition could still be there depending on the loading order and that tinymce's from both bundles (mosaic-remote and plone-bundle-remote) get loaded always. 

* So checking if/how resources are maybe cached,  there is the following now closed issue, it seems to have been implemented by @jensens, but I cannot find the proposed function or a cache busting system in the current implementation:
https://github.com/plone/Products.CMFPlone/issues/3505

* There is this issue of the editor not working and suddenly started to work after restarts:  https://github.com/plone/plone.app.mosaic/issues/524

* I tried to regenerate the plone.app.mosaic resources, but the 3.0.x branch is currently broken as it depends on a select2.patch file which is not in the released @plone/mockup 5.0.5 
https://github.com/plone/plone.app.mosaic/issues/527

@jensens @thet   Something is going on here, but I can't get my digital finger on it yet.

### PR DESCRIPTION
**Pull request by petschki**
fixes #528 

This reuses the registered `pat-tinymce` from patternslib registry. So no imports in the code anymore and therefore no chunk optimization needed. In fact all the tinymce[_plugins]/select2 chunks are removed from this package.

Now there are no more `theme/silver.js` or `langs/xy.js` loading errors and the tiny in the properties modal or in a tile modal are loaded everytime.

### CODE REVIEW

**Review by thet — APPROVED** [review]
LGTM!
:tada:

**Comment by petschki** [comment]
webpack tree before refactoring:
Bildschirmfoto 2023-05-12 um 12 20 59

after:
Bildschirmfoto 2023-05-12 um 12 21 37

I think reusing the patternslib registry is mandatory for addon developers in order to minize the dependecies and chunks.

**Comment by petschki** [comment]
one more step here: refactored the `Modal` implementation to reuse `registry.patterns["plone-modal"]` now all mosaic patterns are gone in the chunks. 🎉

Bildschirmfoto 2023-05-12 um 12 34 47

**Comment by petschki** [comment]
@frapell I've reverted the `Modal` refactoring for now.

**Comment by frapell** [comment]
@petschki This appears to be working fine now. Should I merge?

**Review by frapell — APPROVED** [review]

**Pull request merged**
