### PR TITLE
Allow to put custom css in rows

### PR DESCRIPTION
**Pull request by frapell**
This closes gh-372

Bear in mind that this branch was cut from branch https://github.com/plone/plone.app.mosaic/tree/frapell-subcolumns so, if https://github.com/plone/plone.app.mosaic/pull/371 Is not going to be merged, I will need to cut this from master and apply my changes for this PR

### CODE REVIEW

**Comment by frapell** [comment]
Ok, #371 was merged, so this can be merged in directly to master

**Comment by datakurre** [comment]
Another nice feature many have asked, but I've considered too advanced for my users :) How does this work UX wise?

**Comment by frapell** [comment]
@datakurre there's a screencast in the gh-372. I'm pasting it here for you 

https://www.dropbox.com/s/6b7z0agqmepa7m0/mosaic_custom_css.mkv?dl=0

I think is pretty intuitive, what do you think?

**Comment by datakurre** [comment]
:+1:

@frapell Really nice. Thank you! I'm so happy to see you being able to contribute Mosaic editor. I know, It's messy, but it works until some miracle gives us infinite resources to reinvent it :) (Rob has created a new react version, but it's a very long shot to use it with the current Barceloneta based UI and it does not support TinyMCE.)

**Comment by frapell** [comment]
@datakurre I have to admit being a bit intimidated at first by the amount of JS... However it was super easy to understand, kudos to you on that !! :D

@jensens Want to review and merge?

**Comment by datakurre** [comment]
Mosaic JS is not by me, but mostly by Rob (original design from 2008) and Nathan (refactoring for Castle CMS in 2016). My main contribution was in completing the backend :)

**Pull request merged**
