### PR TITLE
Allow to create Sub-Columns

### PR DESCRIPTION
**Pull request by frapell**
This closes gh-240

### CODE REVIEW

**Comment by jensens** [comment]
LGTM - ready for merge?

**Comment by frapell** [comment]
@jensens Yes, but I would like to hear confirmation from Asko

**Comment by datakurre** [comment]
I admit that I have not tested this myself, but changesets LGTM. We discussed about some UX issues, I supported merging this, because this should not harm existing users.

**Comment by frapell** [comment]
@jensens All yours :)

**Comment by datakurre** [comment]
@frapell Did we implement stickyness also for CTRL?

**Comment by datakurre** [comment]
@frapell I found a computer, where CTRL-down is working, but CTRL-up does not fire, which leaves the inner-subcolumn-marker class forever. Have you seen this?

**Comment by datakurre** [comment]
Tested at https://www.quirksmode.org/dom/events/tests/keys.html that CTRL does firing on key up on this machine / chromium. I wonder, how usual that is.

**Comment by datakurre** [comment]
That made me think of an alternative UX:

While dragging a new tile, pressing ctrl toggles marker on that tile that it would create a subgrid.

If I start seeing more accidental innergrids (becaus of ctrl up not releasing it properly), I need to try that.

**Comment by frapell** [comment]
@datakurre Mmmm... never saw that happening and not sure how it could be broken like that...

I think implementing it as "sticky" should work fine, however I think it should be very clear from the UI that the "subgrid" mode is enabled.

**Comment by datakurre** [comment]
@frapell Oh, sorry, I just wanted to check that it is not sticky. Because of those very reasons.

I'm still puzzled by Ctrl only firing on keydown on that machine. Good to know that you have not seen that.

**Comment by frapell** [comment]
@datakurre Ahh, I see, I confirm it is not sticky (ie. it will add a subgrid only when holding Ctrl) and no, I never saw a key firing the keydown but not the keyup. I'll be curious, is this only happening with Ctrl? or with any other key?

**Pull request merged**
