### PR TITLE
Replace Mosaic rich text formatting actions with inline TinyMCE toolbar actions

### PR DESCRIPTION
**Pull request by datakurre**
Fixes https://github.com/plone/plone.app.mosaic/issues/110 and https://github.com/plone/plone.app.mosaic/issues/88

This may still need review, human testing and more work.

nayttokuva 2015-08-09 kello 2 58 20

### CODE REVIEW

**Comment by datakurre** [comment]
If we merge this, the Mosaic top toolbar starts looking pretty empty and lonely. On the other hand, now there is a lot of room for custom tile and row specific styles (like alternating row backgrounds), and it should also be possible to "favorite" tile / row styles into shortcut buttons (between "Properties" and "Format").

**Comment by datakurre** [comment]
This does introduce a possible usability issue with tile removal [x], because it overlaps with the floating toolbar. (That's why I configured undo / redo actions onto the rigth end of the toolbar.)

**Comment by datakurre** [comment]
Possible issue: TinyMCE does not allow control over link modal features and now the modal will always include also image upload.

**Comment by datakurre** [comment]
Also, because I choosed to follow the existing configuration model, the configuration is pretty verbose in registry xml.

**Comment by datakurre** [comment]
Another possible issue are keyboard shortcuts. Mosaic Editor has it's own shortcut handling and haven't checked does it work and could it work with TinyMCE's shortcuts.

**Comment by datakurre** [comment]
A small update: TinyMCE keyboard shortcuts seem to be working. Added example table structure tile. I still try to avoid adding menus into those inline TinyMCE editors with floating toolbars and therefore I added support for optional contextmenu actions (if such is configured, contextmenu-plugin is enabled). Toolbarless table tile is an example:

nayttokuva 2015-08-09 kello 21 28 55

**Comment by datakurre** [comment]
@vangheem @djay How do you think about moving to inline tinymce toolbars for formatting? (Dylan has already proposed it.) And about TinyMCE menus and context menus? Why is TinyMCE context menu disabled by default in Plone?

Any easy ideas, how we could enhance the top toolbar if rich text formatting moves to inline toolbars? (I still like that Tile and Row related operations would stay there.)

Since tile removal X and inline toolbar overlap, should we move tile removal into the top toolbar? Currently, it's quite easy to accidentally remove a tile.

**Comment by vangheem** [comment]
@datakurre that sounds like a fine idea.

Context menus maybe just aren't enabled by default? I don't remember.

Yes, move "X" tile removal to top of toolbar.

**Comment by datakurre** [comment]
Good to hear that it fits for you too. I'll add that remove button move into this pull soonish and the this is done.

**Comment by datakurre** [comment]
http://picpaste.com/thumbs/mosaic-remove-action-8gMoVB4v.1439234113.png

**Pull request merged**
