### PR TITLE
WIP: support Plone 5.2.x for py2.7 and python3

### PR DESCRIPTION
**Pull request by petschki**
OK ... lets bring it to Plone 5.2/py2/py3

dependencies:
- [x] https://github.com/plone/plone.app.blocks/pull/71
- [x] https://github.com/plone/plone.subrequest/issues/21
- [x] https://github.com/plone/plone.app.drafts/pull/7
- [x] https://github.com/plone/plone.app.tiles/pull/26

### CODE REVIEW

**Comment by petschki** [comment]
@fredv I saw you already did some changes regarding IRichtTextBehavior here https://github.com/plone/plone.app.mosaic/commit/e2189980b99442fab4e2d9ce1224754f2cebc6c4 ... maybe you're willing to bring them to this branch?

**Comment by agitator** [comment]
@petschki https://github.com/plone/plone.subrequest/issues/21 probably needs to be fixed too make it work for "Plone 5.2.x py2.7 py3"

**Comment by fredv** [comment]
@petschki I think you meant to mention @fredvd 
Cheers

**Comment by petschki** [comment]
@fredv ah sorry!

**Comment by petschki** [comment]
@pbauer erm ... do you have eventually an idea, why the travis checks are gone since my last `.travis.yml` changes ?

**Comment by petschki** [comment]
Test for python 3 are almost green. One thing I don't know how to solve is the ConfigParser issue with multiple sections with the same name. Since python 3 there is an internal property `self._proxies` which doesn't get our `multidict` keys right and fails to remove them correctly ...

```
Error in test test_manager_can_delete_user_layout (plone.app.mosaic.tests.test_manage_layouts.TestManageLayouts)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/peterm/workspace/coredev52multipy/src/plone.app.mosaic/src/plone/app/mosaic/tests/test_manage_layouts.py", line 72, in test_manager_can_delete_user_layout
    self.portal.restrictedTraverse('@@manage-layouts-from-editor')()
  File "/Users/peterm/workspace/coredev52multipy/src/plone.app.mosaic/src/plone/app/mosaic/browser/editor.py", line 65, in __call__
    return self.deletelayout()
  File "/Users/peterm/workspace/coredev52multipy/src/plone.app.mosaic/src/plone/app/mosaic/browser/editor.py", line 100, in deletelayout
    removeLayout(manifest, filename)
  File "/Users/peterm/workspace/coredev52multipy/src/plone.app.mosaic/src/plone/app/mosaic/browser/editor.py", line 51, in removeLayout
    parser.remove_section(section)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 953, in remove_section
    del self._proxies[section]
KeyError: 'contentlayout1'

```

@vangheem  since you've implemented the `multidict` feature in `plone.app.blocks` do you have any pointers for me how to solve this?

**Comment by petschki** [comment]
Whoa ... sorry. Somehow my codehub App merged this PR ... sorry for that. I‘ve reverted it already.

**Comment by jensens** [comment]
Confusing, so this is in fact open?

**Comment by petschki** [comment]
sorry for the confusion here. This is all work in progress. Still some failing tests I'm fighting with. I'll create a new PR this weekend.

**Comment by MrTango** [comment]
nice work thx

**Pull request merged**
