### PR TITLE
Added ability for a layout to have a maximum amount of columns set

### PR DESCRIPTION
**Pull request by neilferreira**
Defaults to the current amount of  4.

The current functionality limits the max columns to 4 but still allows users to keep dropping more columns and it feels rather buggy.  This disabled disable the ability to drop another tile on the left or right if the max has been reached.

### CODE REVIEW

**Comment by gforcada** [comment]
:+1: being able to override that per layout, that's a great idea.

**Comment by jensens** [comment]
CLA is missing

**Comment by datakurre** [comment]
@neilferreira Sorry for late review.

* add changelog lin (CLA)
* fix to keep the current behavior as default (which should happen, when there is no ``obj.data('max-columns')``

**Comment by neilferreira** [comment]
@datakurre 
CLA has been signed
The current behaviour is already implemented, see https://github.com/plone/plone.app.mosaic/pull/168/files#diff-72919b38f6dfb1d231621b34df97005aR23

I'll add a changelog entry as soon as I get time.

**Comment by datakurre** [comment]
@neilferreira I added the changelog note. Thanks!

**Pull request merged**
