### PR TITLE
Gsoc17 inline tile

### PR DESCRIPTION
**Pull request by mikkohu**
One of the pull reuqests for my Summer of Code project. This pull requests includes the functionality to drag tiles in and out of rich text tiles.

Biggest changes are added event bindings on mosaic.layout, inserting tiles into tinyMCE editors, and saving and initializing inline-tiles. Most changes are on the mosaic.tile.js and mosaic.layout.js

To render inline tiles in view mode, standardtile branch datakurre-flatten-html is required. Rendering tiles as spans in view mode doesn't work yet.

Additional info and video demonstrations about the related project can be found at [my final report](http://mikkohugsoc.blogspot.fi/2017/08/improved-list-customization-using.html)

Known bugs: 
-Inline tiles that are spans are duplicated when dragged inside the tinymce editor. This is at least partially caused by nonEditable-plugin. A possible fix could be to check for duplicate elements on inline tiles dragend and remove them

-When draggin tiles inside rich text tiles, they sometimes become child elements for tile borders. This is really rare bug and thus hard to debug. Inserting tiles is done using tinyMCE:s own insertContent -command so this shouldn't really happen but for some reason it does...

### CODE REVIEW

**Comment by MrTango** [comment]
@mikkohu didn't you sign the contributor agreement?

**Comment by mikkohu** [comment]
I did sign a contributor agreement last year for GSOC. I'm not sure why roboto is failing the builds.

**Comment by MrTango** [comment]
@gforcada could you please have a look over the agreement issue.
@datakurre we should merge this, if it's ready or do you know more aboute the status here?
@mikkohu could you please complete the PR by providing a changelog entry.

**Comment by gforcada** [comment]
I'm flying this weekend with kids and no laptop, I will have a look next week

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
